// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetCurrentUser() {
  return window['go']['main']['App']['GetCurrentUser']();
}

export function GetMyAttendance() {
  return window['go']['main']['App']['GetMyAttendance']();
}

export function GetMyTasks() {
  return window['go']['main']['App']['GetMyTasks']();
}

export function Login(arg1, arg2) {
  return window['go']['main']['App']['Login'](arg1, arg2);
}

export function Logout() {
  return window['go']['main']['App']['Logout']();
}

export function SetNewPassword(arg1, arg2) {
  return window['go']['main']['App']['SetNewPassword'](arg1, arg2);
}

export function ShowWindow() {
  return window['go']['main']['App']['ShowWindow']();
}

export function SignIn(arg1) {
  return window['go']['main']['App']['SignIn'](arg1);
}

export function SignOut() {
  return window['go']['main']['App']['SignOut']();
}
