// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {api} from '../models';
import {state} from '../models';
import {auth} from '../models';

export function GetCurrentUser():Promise<api.User>;

export function GetMyAttendance():Promise<state.Attendance>;

export function GetMyTasks():Promise<Array<api.Task>>;

export function Login(arg1:string,arg2:string):Promise<auth.LoginResult>;

export function Logout():Promise<void>;

export function SetNewPassword(arg1:string,arg2:string):Promise<void>;

export function ShowWindow():Promise<void>;

export function SignIn(arg1:api.StartTimerData):Promise<state.Attendance>;

export function SignOut():Promise<state.Attendance>;
